# Generated by Django 3.2.2 on 2021-05-15 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='appointment',
            new_name='appointment_table',
        ),
    ]
