# Generated by Django 3.2.2 on 2021-05-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_appointment_appointment_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment_table',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
