# Generated by Django 3.2.2 on 2021-05-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='help',
            name='user_email',
            field=models.EmailField(default='test@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
