# Generated by Django 3.2.2 on 2021-05-17 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_help_user_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='help',
            new_name='helpandsupport',
        ),
    ]
