# Generated by Django 3.2.2 on 2021-05-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_help_helpandsupport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpandsupport',
            name='message',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
