# Generated by Django 3.2.2 on 2021-05-23 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_doctor_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='Email',
            new_name='email',
        ),
    ]
