# Generated by Django 3.2.2 on 2021-06-02 03:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_rename_email_doctor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment_table',
            name='apply_date',
            field=models.DateField(default=datetime.date(2021, 6, 2)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment_table',
            name='status',
            field=models.CharField(choices=[('A', 'Approved'), ('NA', 'Not Approved'), ('P', 'Pending')], default='P', max_length=2),
        ),
    ]
