# Generated by Django 3.2.2 on 2021-06-02 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20210602_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment_table',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
