# Generated by Django 3.2.2 on 2021-06-03 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_appointment_table_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment_table',
            name='disease_id',
        ),
    ]
