# Generated by Django 3.2.2 on 2021-06-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_appointment_table_disease_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorname', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('postdate', models.DateField(null=True)),
                ('image', models.ImageField(null=True, upload_to='blog/')),
            ],
        ),
    ]
