# Generated by Django 3.2.2 on 2021-06-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_blogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='address',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospital',
            name='opening_hrs',
            field=models.CharField(default='24 hours', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospital',
            name='specialization',
            field=models.CharField(default='Neurology', max_length=10),
            preserve_default=False,
        ),
    ]
