# Generated by Django 3.2.2 on 2021-06-07 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_hospital_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='no_of_beds',
        ),
    ]
