# Generated by Django 3.2.2 on 2021-06-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_remove_hospital_no_of_beds'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='location',
            field=models.TextField(null=True),
        ),
    ]
