# Generated by Django 3.2.2 on 2021-06-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_hospital_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='contact',
            field=models.IntegerField(null=True),
        ),
    ]
