# Generated by Django 3.2.2 on 2021-06-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_hospital_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='labs',
            name='contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='labs',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
