# Generated by Django 3.2.2 on 2021-06-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_auto_20210608_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='labs',
            name='location',
            field=models.TextField(null=True),
        ),
    ]
