# Generated by Django 3.2.4 on 2021-06-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_labs_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseases',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
