# Generated by Django 3.2.2 on 2021-06-10 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_diseases_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='chat_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.TimeField()),
                ('days_left', models.IntegerField()),
                ('status', models.CharField(choices=[('A', 'Active'), ('NA', 'Not Active')], default='A', max_length=2)),
                ('is_active', models.BooleanField()),
                ('doctor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.doctor')),
                ('patient_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.patient')),
            ],
        ),
    ]
