# Generated by Django 3.1.2 on 2021-06-12 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_auto_20210612_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='appointment_id',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='myapp.appointment_table'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='From',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='message',
            name='to',
            field=models.EmailField(max_length=100),
        ),
    ]
