# Generated by Django 3.1.2 on 2021-06-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_auto_20210612_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='Attachement',
        ),
        migrations.AddField(
            model_name='message',
            name='Attachment',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
